database: &database
  adapter: postgresql
  host: localhost
  port: 6543
  timeout: 5000
  database: counterdb2
  username: macbookpro
  password: Dung123#
  schema_search_path: "public, <%= Store::VIEW_PROJECTION.schema_name %>"

development:
  <<: *database
  pool: 5

test:
  adapter: postgresql
  host: localhost
  port: 6543
  timeout: 5000
  database: test_counterdb2
  username: macbookpro
  password: Dung123#
  schema_search_path: "public, <%= Store::VIEW_PROJECTION.schema_name %>"

